### ISSUE TITLE
Autosaving sometimes saves corrupted data

### ISSUE THREAD

**Issue by Lordmau5** [gta-chaos-mod/ASI-script#1]
After certain missions the game potentially still has some threads running that, when being saved, will cause the game to crash upon loading it.

Known missions:
- After End Of The Line (Part 2) *(when the chase starts)*

**Comment by nukecorruption** [comment]
Another one: https://clips.twitch.tv/TallCallousTarsierCorgiDerp
Savefile: 
[chaos_autosave.zip](https://github.com/gta-chaos-mod/ASI-script/files/3654617/chaos_autosave.zip)
