### ISSUE TITLE
GTA SA 1.0 hoodlum

### ISSUE THREAD

**Issue by RockeyWereWolf** [gta-chaos-mod/ASI-script#16]
The mod just doesn't want to worл. After starting GTA sa, I launch the .exe mode. In the game, I start a new game (a strip of time and the inability to download the game are available). I press start in the exe file and the program runs a strip of time, but the game does not, and the effects are not activated at the right time.

**Comment by Lordmau5** [comment]
Can you try running the Chaos Mod `.exe` as administrator?
It could be that your normal user account doesn't have permissions to properly use it

**Comment by RockeyWereWolf** [comment]
And how did I not think of it myself? I’m launching GTA as an administrator and therefore the program cannot "enter effects in it". I'll try.

**Comment by RockeyWereWolf** [comment]
Thnx, it üorking now.
