### ISSUE TITLE
Game crashing on LS and LV airports

### ISSUE THREAD

**Issue by nukecorruption** [gta-chaos-mod/ASI-script#21]
Since Green Sabre mission (actually I think since Madd Dogg's Rhymes mission or a mission earlier), during Badlands missions (NMG speedrun route) every time I go near Shamals in LS airport the game crashes when spawning them in. Same thing with LV airport when going near the Dodo or whatever it was called but Shamals there work fine and vice versa with LS airport, Dodo spawning doesnt crash the game.

I dont know if this is because of my system, Win7 64bit, no SSD or that my Chaos timer is on 10 seconds? No idea
That was playing on original SA copy but I installed steam version and downgraded it just to test out if it crashes on that too and it does.

BTW, I'm new to github, how do I mark something as "bug" or whatever?

EDIT: I tested a bit and I think it starts crashing after alot of effects have been activated and deactivated because what I tested activating +5 cheats in a row every 10 seconds and going to airport or teleporting there doesn't crash when going near those spawns. Also I have all effects on except some vehicle spawns because that seems to be related somehow since they cause crashing too.
13 mins in with 10 second timer, got teleported to LV airport and going near the Dodo crashed the game, so that's like 78 effects

**Comment by Lordmau5** [comment]
That's something in regards to the `Invisible Vehicles` effect and has already been fixed in-dev :)
So v1.1.4 will have that fixed - thank you for bringing it up though! I really appreciate it :D
