### ISSUE TITLE
Photo Opportunity Softlocks

### ISSUE THREAD

**Issue by Lordmau5** [gta-chaos-mod/ASI-script#26]
During the "camera mode" on Photo Opportunity, several effects can mess with the player and softlock them.

This is likely due to the player being on a "turret" and not being able to move.

Gotta special case that maybe?

**Comment by KovRick** [comment]
Please answer, your mod does not connect with tweak, you can help or lay out instructions on what and how to do, I enter everything correctly, it says that it is not the right name or token.

**Comment by Lordmau5** [comment]
> Please answer, your mod does not connect with tweak, you can help or lay out instructions on what and how to do, I enter everything correctly, it says that it is not the right name or token.

Please create a new issue and don't reply to already existing ones that don't have anything to do with your problem. (Also, reading through it, it would be good if you could attach a screenshot of the Twitch tab of the UI in said new issue)
