### ISSUE TITLE
Lag spikes

### ISSUE THREAD

**Issue by Haellm** [gta-chaos-mod/ASI-script#48]
When running without frame limiter, game just has these lag spikes whenever I'm doing anything (even when I'm in the options menu).

**Comment by Lordmau5** [comment]
What are your PC specs?
As in, your CPU, GPU, RAM, ...

**Comment by Haellm** [comment]
> What are your PC specs?
> As in, your CPU, GPU, RAM, ...

ryzen 3 1200, 8gb ram, rx 570 8gb

**Comment by Haellm** [comment]
> What are your PC specs?
> As in, your CPU, GPU, RAM, ...

actually resolved by running BOTH gta sa and chaos mod as administrator

**Comment by Lordmau5** [comment]
Glad to hear you got it resolved 😁
