### ISSUE TITLE
High pitched audio messes up cutscenes

### ISSUE THREAD

**Issue by LapisOnTheMoon** [gta-chaos-mod/ASI-script#54]
Seen here: https://clips.twitch.tv/BetterPlausiblePuddingGivePLZ

I also tested it on the Big Smoke cutscene and the audio was playing before it should have when the effect is active.

**Comment by Lordmau5** [comment]
This is because it doesn't modify *just* the pitch but also the speed of the audio / sounds playing.

Nothing I can do about it.
