### ISSUE TITLE
mod .exe file fails to launch

### ISSUE THREAD

**Issue by Remolit** [gta-chaos-mod/ASI-script#55]
The mod .exe can not run - process works for 2 seconds, nothing is displayed and then it dies completely. Scripts themselves are working.
Administator permissions do nothing.
Bug occurs with every mod version.

[GTA SA Chaos Mod.exe.10552.zip](https://github.com/gta-chaos-mod/ASI-script/files/3775805/GTA.SA.Chaos.Mod.exe.10552.zip)

**Comment by Lordmau5** [comment]
Sounds to me like you have an antivirus program that doesn't want the executable to run.

**Comment by Remolit** [comment]
Doesn't seem like that's the case, still can't run it even with antivirus and Windows Defender disabled.

**Comment by Lordmau5** [comment]
What are your PC specs?
You mentioned Windows Defender, so we can rule out that you aren't on Windows 10.

Did you make sure that you have the newest .NET Framework installed (or rather, at least the version I have linked in the readme?)

**Comment by Remolit** [comment]
Apparently I had a v4.6+ Framework installed, and could not install the 4.7 one. 
I am actually using Windows 10, but a version that's outdated by one and a half years... I'll see if that fixes it and report back.

**Comment by Remolit** [comment]
Seems to have worked, thanks for reminding that an outdated .NET Framework could be an issue.
