### ISSUE TITLE
Pass Current Mission Not Working

### ISSUE THREAD

**Issue by Tiqsx** [gta-chaos-mod/ASI-script#57]
Whenever i get the pass mission effect, nothing happens and the text is grayed out. I have both the real and fake mission pass effect ticked.

**Comment by Lordmau5** [comment]
Then you might just be out of luck and you're getting the fake one constantly.

You can tell that it's a fake one if you get back into a mission after it happened and it turns into `Pass Current Mission?` (see the question mark at the end)

**Comment by Tiqsx** [comment]
I just toggled the effects off and on again and I eventually got the real mission pass and it counted so I don’t know happened but problem fixed now :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Lordmau5** [comment]
Glad to hear you got it fixed in that case! :D
