### ISSUE TITLE
Cant Login on twitch 

### ISSUE THREAD

**Issue by okanieba55** [gta-chaos-mod/ASI-script#58]
I try to log on the mod window but i dont let me its says that the password or username is wrong but its not,i checked it. i dont know whats causing the issue.

**Comment by Lordmau5** [comment]
The problem lies within you trying to enter your password whereas it clearly asks for an OAuth Token.

Use a website like https://twitchtokengenerator.com/ with a custom scope token on `chat:read` and `chat:edit` at the bottom of the page, then authenticate with that and use the token you get from that.

**Comment by okanieba55** [comment]
Oh, i didnt know that. Thanks for the help!

**Comment by Lordmau5** [comment]
No problem - did you end up getting it working through that method then? :)

**Comment by okanieba55** [comment]
another problem,im trying with some Friends but they cant vote the effecs

**Comment by okanieba55** [comment]
maybe i need to have a bot for that?

**Comment by Lordmau5** [comment]
This can have multiple reasons:
- You aren't entering the correct channel in the `Channel:` input in which the mod will send / read messages
- The OAuth Token you generated doesn't have the specific scopes `chat:read` and / or `chat:edit`

**Comment by okanieba55** [comment]
In channel i put the twitch account or other thing?

**Comment by Lordmau5** [comment]
Yes, that's the Twitch channel.

So if you'd want to run it on your own channel with your own account, you'd put in the following (in my case):
- Channel: `lordmau5`
- Username: `lordmau5`
- OAuth Token: _Generated from the twitchtokengenerator website_

**Comment by okanieba55** [comment]
Thanks! it worked perfectly :)

**Comment by Lordmau5** [comment]
Glad you got it working in that case!
Good luck on the madness ;)

**Comment by BartoszOblinski** [comment]
Hi! I have a problem with this mod. I connected everything properly, generated a token, connects to Twitch chat, but when voting, it does not return information to the game and nothing happens. I don't know what's going on... Any ideas? I am using the latest mod and the game is version 1.0
