### ISSUE TITLE
I cannot open the GTA Trilogy Chaos Mod

### ISSUE THREAD

**Issue by rbskurt** [gta-chaos-mod/ASI-script#63]
Pretty self explenatory, cant open the .exe 
Game doesnt crash

**Comment by Lordmau5** [comment]
Which part can't you open?
The game, as in GTA:SA itself, or do you mean the .exe that is used for the effects and such?

Try opening the GTA Trilogy Chaos Mod.exe as admin

**Comment by rbskurt** [comment]
the trilogy chaos mod.exe
do i need the framework to open it?
i thought i installed the 4.7.2 framework but i havent

**Comment by Lordmau5** [comment]
I mean, yeah, the framework is required - though iirc it should throw an error instead of just ... not opening at all?

**Comment by Lordmau5** [comment]
Is it working now? If so, I'd go ahead and close this issue.

**Comment by rbskurt** [comment]
yeah works now you can close it

Lordmau5 <notifications@github.com> schrieb am Do., 16. Jan. 2020, 17:14:

**Comment by Lordmau5** [comment]
Perfect! Glad you got it working :)

**Comment by AbDoooHAi** [comment]
i have the same problem i installed net framework and didnt work

**Comment by Lighns0gn** [comment]
Hey when i try to open chaos mod application it shows that it stopped working but in the game the timer stays at 00:00
