### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by DavisBlue** [gta-chaos-mod/ASI-script#65]
Hi, I am unable to launch the game with the Chaos Mod script. More specifically, the logos show up, however when the menu should show up, the game crashes.
I followed the instructions to use the ASI Ultimate Loader, so here are the generated Crash Dump files:
[CrashDumps.zip](https://github.com/gta-chaos-mod/ASI-script/files/4082513/CrashDumps.zip)

**Comment by Lordmau5** [comment]
- Did you downgrade to 1.0? I've heard some people had that issue when being on a higher version.
- Do you have any other mods installed? (Such as different fonts / languages)

**Comment by DavisBlue** [comment]
- I have the version 1.0 bought, so I didn't need to downgrade.
- The only other mod I was using previously was s0beit, however it was not the in GTA SA folder at the time of trying to run this mod.
- I use Windows 7.

**Comment by Lordmau5** [comment]
I have a feeling SA:MP is causing the issues you're facing.
Would it be possible for you to install a clean copy of GTA to a separate folder, then try to install the mod in that one and run that?

**Comment by DavisBlue** [comment]
Thank you, it did indeed work.
