### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Kamikaza404** [gta-chaos-mod/ASI-script#67]
Hi. My game crashes when I press the "Start / Resume" button in the GUI.

I have Windows 7, GTA SA 1.0 with the US exe from speedrun.com
.NET Framework 4.7.2 is installed.
Also tried downgrading steam version with the same results.

[CrashDumps.zip](https://github.com/gta-chaos-mod/ASI-script/files/4113013/CrashDumps.zip)

**Comment by Lordmau5** [comment]
A quick glance over the crash log shows me that it has problems running a `ReadFile` method.

Could you try running GTA:SA as an administrator?
I feel it's a lack of permissions in regards to the messaging pipeline I have from the Mod to the GUI

**Comment by Kamikaza404** [comment]
When I only open the game as an administrator, nothing happens. When I open both the game and the GUI as an administrator, same crash happens.

[CrashDumps.zip](https://github.com/gta-chaos-mod/ASI-script/files/4113548/CrashDumps.zip)

**Comment by Lordmau5** [comment]
Alright, can you please try with 2.1.1?
A friend of mine had the exact same issue and it appears to have stemmed from Windows 7 not supporting certain default variables for the new communication library I used.

2.1.1 works for him :)

**Comment by Kamikaza404** [comment]
Yep, it works now. Thank you!

**Comment by LuxSerg** [comment]
Can you help me too pls? I have the same issue. What is 2.1.1?
